import { describe, expect, it } from "vitest";
import {
  FEATURED_SLUGS,
  HUB_SLUGS,
  REMAINING_SLUGS,
  hubCoversEveryTreatment,
  treatmentDetailPath,
} from "./treatmentLinks";
import { treatments } from "@/data/treatments";
import { treatmentPages } from "@/data/treatmentPages";
import { PREVENTION_RELATED_SLUGS } from "@/data/preventionContent";
import { localizePath } from "./i18n/routing";
import en from "./i18n/dictionaries/en";

/**
 * Regression cover for a defect that reached production on the reference
 * site: treatment detail pages shipped with no inbound internal links because
 * the hub linked its cards to `/contact`. These tests assert the link graph
 * itself, not the markup, so they run without a DOM.
 */

/** Treatments whose information page is not generated by [slug], and where it lives. */
const OWN_ROUTE: Record<string, string> = {
  "emergency-aesthetic-dentistry": "/treatments/emergency-aesthetic-dentistry",
  "preventive-care": "/prevention-hygiene",
};
const HAND_BUILT = Object.keys(OWN_ROUTE);
const expectedPath = (slug: string) => OWN_ROUTE[slug] ?? `/treatments/${slug}`;

const DRAFT_SUFFIX = " | Dentacare Aruba (Draft)";

describe("hub covers the catalogue", () => {
  it("presents every treatment exactly once, across both sections", () => {
    expect(hubCoversEveryTreatment()).toBe(true);
    expect(HUB_SLUGS).toHaveLength(treatments.length);
  });

  it("has no duplicate destinations", () => {
    const paths = HUB_SLUGS.map(treatmentDetailPath);
    expect(new Set(paths).size).toBe(paths.length);
    const overlap = FEATURED_SLUGS.filter((s) => (REMAINING_SLUGS as readonly string[]).includes(s));
    expect(overlap).toEqual([]);
  });
});

describe("every detail page has an inbound hub link", () => {
  it("covers each generated treatment page", () => {
    for (const slug of Object.keys(treatmentPages)) {
      expect(HUB_SLUGS, `no hub link to /treatments/${slug}`).toContain(slug);
    }
  });

  it("covers the hand-built pages too", () => {
    for (const slug of HAND_BUILT) {
      expect(HUB_SLUGS, `no hub link to ${expectedPath(slug)}`).toContain(slug);
    }
  });
});

describe("every hub destination exists", () => {
  it("resolves to a real treatment and a real page", () => {
    const catalogue = new Set(treatments.map((t) => t.slug));
    for (const slug of HUB_SLUGS) {
      expect(catalogue, `${slug} is not in the treatment catalogue`).toContain(slug);
      const hasPage = Boolean(treatmentPages[slug]) || HAND_BUILT.includes(slug);
      expect(hasPage, `${slug} has no detail page`).toBe(true);
    }
  });

  it("has draft-labelled metadata for each destination", () => {
    const meta = en.treatmentsMeta;
    const all = [meta.hub, meta.prevention, meta.emergency, ...Object.keys(treatmentPages).map((slug) => meta.details[slug])];
    for (const entry of all) {
      expect(entry, "missing metadata").toBeDefined();
      expect(entry.title.endsWith(DRAFT_SUFFIX), entry.title).toBe(true);
      expect(entry.description.length).toBeGreaterThan(0);
      expect(entry.description.length).toBeLessThanOrEqual(200);
    }
    expect(Object.keys(meta.details).sort()).toEqual(Object.keys(treatmentPages).sort());
  });
});

describe("no card links to Contact instead of its information page", () => {
  it("builds the information-page path for every treatment", () => {
    for (const slug of HUB_SLUGS) {
      const path = treatmentDetailPath(slug);
      expect(path).toBe(expectedPath(slug));
      expect(path).not.toBe("/contact");
    }
  });

  it("links preventive care to the prevention page, not a /treatments URL", () => {
    expect(HUB_SLUGS.map(treatmentDetailPath)).not.toContain("/treatments/preventive-care");
    expect(treatmentDetailPath("preventive-care")).toBe("/prevention-hygiene");
  });

  it("serves every destination unprefixed in the default language", () => {
    for (const slug of HUB_SLUGS) {
      expect(localizePath(treatmentDetailPath(slug), "en")).toBe(expectedPath(slug));
    }
  });
});

describe("link text", () => {
  const labels = en.treatmentsPage.treatmentLinks as Record<string, string>;

  it("gives every treatment its own label", () => {
    for (const slug of HUB_SLUGS) {
      expect(labels[slug], `label missing for ${slug}`).toBeTruthy();
      expect(labels[slug].length).toBeGreaterThan(3);
    }
  });

  it("does not reuse one phrase for every link", () => {
    const used = HUB_SLUGS.map((slug) => labels[slug]);
    expect(new Set(used).size).toBe(used.length);
  });

  it("keeps anchors off the exact treatment name", () => {
    for (const slug of HUB_SLUGS) {
      const treatment = treatments.find((t) => t.slug === slug)!;
      expect(labels[slug].toLowerCase()).not.toBe(treatment.name.toLowerCase());
    }
  });
});

describe("internal links from other pages", () => {
  it("links the prevention page only to real treatment pages", () => {
    for (const slug of PREVENTION_RELATED_SLUGS) {
      expect(treatmentPages[slug], `${slug} has no page`).toBeDefined();
    }
  });
});
